[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:runtime && npm run build:server"

[deploy]
startCommand = "npm run start:server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

